### ISSUE TITLE
Variables in LESS imports.

### ISSUE THREAD

**Issue by berarma** [markstory/mini-asset#20]
I've just noticed mini-asset won't find dependencies declared with an import that uses a variable in LESS.

I must say I don't really need this to work since the files I'm importing are vendor files that I won't change. Touching my files is enough to rebuild it. Just noticed it and thought I would report about it.

This will be hard to fully resolve. A possible workaround would be to have an option to disable incremental building or a configurable path to check for changes on any file inside it.

**Comment by markstory** [comment]
Could you give an example/sample of problematic files? Are you using node LESS, or the PHP implementations?

**Comment by berarma** [comment]
This is a simple example:

``` less
@root-dir: vendor/twbs/bootstrap/less;
@import "@{root-dir}/bootstrap.less";
```

I'm using node LESS. Compilation works well, it's only that the incremental builds fail to see changes on files imported in this way. Since this imports have to be resolved at compile time I guess it would be hard to know the exact dependencies before compiling.

**Comment by markstory** [comment]
Ah ok. Resolving those variable imports will be nigh on impossible without a sophisticated CSS parser. While the code you have _could_ be solved, other cases like

``` css
// variables.less
@rootdir: some/path

// app.less
@import 'variables.less';
@import "@{rootdir}/other.less";
```

Will not be handled as easily.
